# Generated by Django 4.1.5 on 2023-01-09 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_map_folder_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(142.87041106217137 -36.67650479917193)', geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
