# Generated by Django 4.1.5 on 2023-01-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feature_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.map')),
            ],
        ),
    ]
