# Generated by Django 4.1.5 on 2023-01-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_featuretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.featuretype'),
            preserve_default=False,
        ),
    ]
