# Generated by Django 4.1.5 on 2023-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_type_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
