# Generated by Django 4.1.5 on 2023-01-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_feature_feature_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_type_fields',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
