# Generated by Django 4.1.5 on 2023-01-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_feature_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='feature_type_fields',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='type',
            new_name='geom_type',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='feature_type',
            new_name='schema',
        ),
    ]
