# Generated by Django 4.1.5 on 2023-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_feature_type_fields_features_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='default_symbology',
            field=models.JSONField(default={'colour': '#f20707', 'icon': 'triangle', 'size': 12}),
            preserve_default=False,
        ),
    ]
