# Generated by Django 4.1.5 on 2023-01-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_features_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.featureschemas'),
        ),
    ]
