# Generated by Django 4.1.5 on 2023-01-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_features_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='name',
        ),
    ]
