# Generated by Django 4.1.5 on 2023-01-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_features_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='map',
            new_name='map_id',
        ),
    ]
