# Generated by Django 4.1.5 on 2023-01-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_featureschemas_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureschemas',
            old_name='map',
            new_name='map_id',
        ),
    ]
