# Generated by Django 4.1.5 on 2023-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_features_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureschemas',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
