# Generated by Django 4.1.5 on 2023-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_featureschemas_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
