# Generated by Django 4.1.5 on 2023-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_features_deleted_at_maps_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureschemas',
            name='default_symbology',
            field=models.JSONField(null=True),
        ),
    ]
