# Generated by Django 4.1.5 on 2023-01-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_featureschemas_default_symbology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='default_symbology',
            field=models.JSONField(null=True),
        ),
    ]
