# Generated by Django 4.1.5 on 2023-01-26 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_maps_default_symbology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='maps',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
