# Generated by Django 4.1.5 on 2023-01-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_alter_maps_owner_rename_owner_maps_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureschemas',
            name='map_id',
        ),
        migrations.AddField(
            model_name='featureschemas',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
