# Generated by Django 4.1.5 on 2023-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_featureschemas_map_id_featureschemas_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='visible_schema_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
