# Generated by Django 4.1.5 on 2023-01-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_maps_visible_schema_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='visible_schema_ids',
            new_name='hidden_schema_ids',
        ),
    ]
