# Generated by Django 4.1.5 on 2023-02-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_visible_schema_ids_maps_hidden_schema_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='last_used_schema_id',
            field=models.ForeignKey(db_column='last_used_schema_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.featureschemas'),
        ),
    ]
