# Generated by Django 4.1.5 on 2023-04-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_maps_last_used_schema_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureschemas',
            name='symbology',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
