# Generated by Django 4.1.5 on 2023-04-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_featureschemas_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureschemas',
            name='symbology',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
