# Generated by Django 4.1.5 on 2023-04-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_featureschemas_symbology'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='symbol_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
