# Generated by Django 4.1.5 on 2023-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_features_symbol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='favourited_symbols',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
