# Generated by Django 4.1.5 on 2023-04-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_maps_favourited_symbols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='favourited_symbols',
        ),
    ]
