# Generated by Django 4.2.1 on 2023-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_rename_hidden_schema_ids_historicalmaps_available_schema_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureschemas',
            name='recently_used_symbols',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalfeatureschemas',
            name='recently_used_symbols',
            field=models.JSONField(null=True),
        ),
    ]
