# Generated by Django 4.2.1 on 2023-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_featureschemas_recently_used_symbols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureschemas',
            name='recently_used_symbols',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeatureschemas',
            name='recently_used_symbols',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
