# Generated by Django 4.2.1 on 2023-06-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_featureschemas_recently_used_symbols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_gdrive_backup',
            field=models.DateTimeField(null=True),
        ),
    ]
