# Generated by Django 4.2.1 on 2023-06-05 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_profile_last_gdrive_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='featureschemas',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalfeatures',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfeatureschemas',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaps',
            name='last_updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maps',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
