# Generated by Django 4.2.5 on 2023-09-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_features_last_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfeatures',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
