# Generated by Django 4.2.5 on 2023-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_features_imported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='import_job',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalfeatures',
            name='import_job',
            field=models.TextField(blank=True, default=''),
        ),
    ]
