# Generated by Django 4.2.7 on 2023-11-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_features_import_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaps',
            name='hero_icon',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='hero_icon',
            field=models.JSONField(null=True),
        ),
    ]
