# Generated by Django 4.2.11 on 2024-05-11 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_historicalmaps_hero_icon_maps_hero_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_whats_new_view',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
