# Generated by Django 4.2.11 on 2024-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_profile_last_whats_new_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_whats_new_view',
        ),
        migrations.AddField(
            model_name='profile',
            name='whats_new_release_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
