# Generated by Django 4.2.11 on 2024-05-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_features_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalfeatures',
            name='creation_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
