# Generated by Django 4.2.11 on 2024-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_featureschemas_recently_used_symbols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whats_new_release_count',
            field=models.IntegerField(default=0),
        ),
    ]
