# Generated by Django 4.2.11 on 2024-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_profile_whats_new_release_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaps',
            name='starting_location',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='starting_location',
            field=models.JSONField(null=True),
        ),
    ]
