# Generated by Django 4.2.11 on 2024-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_historicalmaps_starting_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmaps',
            name='starting_location',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='starting_location',
        ),
        migrations.AddField(
            model_name='historicalmaps',
            name='starting_location_centre',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalmaps',
            name='starting_location_zoom',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='starting_location_centre',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='starting_location_zoom',
            field=models.FloatField(default=None, null=True),
        ),
    ]
