# Generated by Django 4.2.11 on 2024-08-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_historicalmaps_starting_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmaps',
            name='starting_location_centre',
        ),
        migrations.RemoveField(
            model_name='historicalmaps',
            name='starting_location_zoom',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='starting_location_centre',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='starting_location_zoom',
        ),
    ]
