# Generated by Django 4.2.11 on 2024-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_historicalmaps_starting_location_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaps',
            name='location_search_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maps',
            name='location_search_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
