version: 2
updates:
  - package-ecosystem: pip
    directory: "/django"
    schedule:
      interval: weekly
      day: saturday
      time: "09:30"
      timezone: Australia/Perth
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
      day: saturday
      time: "09:30"
      timezone: Australia/Perth
    open-pull-requests-limit: 99
  ignore:
  # ESLint 8 => 9 ecosystem is way too brittle and fiddly to configure all of the plugins
  # Not a yak worth shaving.
  - dependency-name: "@typescript-eslint/eslint-plugin"
  - dependency-name: "eslint"
  - dependency-name: "eslint-config-airbnb"
  - dependency-name: "eslint-config-airbnb-typescript"
  - dependency-name: "eslint-config-prettier"
  - dependency-name: "eslint-import-resolver-typescript"
  - dependency-name: "eslint-plugin-import"
  - dependency-name: "eslint-plugin-jsx-a11y"
  - dependency-name: "eslint-plugin-prettier"
  - dependency-name: "eslint-plugin-react"
  - dependency-name: "eslint-plugin-react-hooks"
