repos:
  - repo: local
    hooks:
      - id: eslint
        language: system
        name: eslint
        entry: cd frontend && npm run --cwd=frontend lint
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]
