repos:
  - repo: local
    hooks:
      - id: biome
        language: system
        name: biome
        entry: cd frontend && pnpm biome lint
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]
