repos:
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: cd frontend && npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]