repos:
  - repo: local
    hooks:
      - id: eslintz
        language: system
        name: eslint
        entry: cd frontend && yarn run foobar
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]
