repos:
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: cd frontend && pnpm biome check --error-on-warnings --log-level=debug --verbose
        language: system
        types: [text]