repos:
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: bash -c 'cd frontend && pnpm biome check --error-on-warnings'
        language: system
        types: [text]