import {
  Accessibility,
  AccessibilitySign,
  AccessibilityTech,
  Activity,
  AddCircle,
  AddDatabaseScript,
  AddFolder,
  AddFrame,
  AddHexagon,
  AddKeyframe,
  AddKeyframeAlt,
  AddKeyframes,
  AddLens,
  AddMediaImage,
  AddMediaVideo,
  AddPage,
  AddPageAlt,
  AddPinAlt,
  AddSelection,
  AddSquare,
  AddToCart,
  AddUser,
  AfricanTree,
  AirConditioner,
  Airplane,
  AirplaneHelix,
  AirplaneHelix45Deg,
  AirplaneOff,
  AirplaneRotation,
  Airplay,
  Alarm,
  Album,
  AlbumCarousel,
  AlbumList,
  AlbumOpen,
  AlignBottomBox,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignLeftBox,
  AlignRight,
  AlignRightBox,
  AlignTopBox,
  AngleTool,
  Antenna,
  AntennaOff,
  AntennaSignal,
  AntennaSignalTag,
  AppNotification,
  AppWindow,
  Apple,
  AppleHalf,
  AppleHalfAlt,
  AppleImac2021,
  AppleImac2021Side,
  AppleMac,
  AppleSwift,
  AppleWallet,
  ArSymbol,
  Arcade,
  Archery,
  ArcheryMatch,
  Archive,
  AreaSearch,
  ArrowArchery,
  ArrowBlCircle,
  ArrowBlSquare,
  ArrowBrCircle,
  ArrowBrSquare,
  ArrowDown,
  ArrowDownCircle,
  ArrowEmailForward,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowRight,
  ArrowRightCircle,
  ArrowSeparate,
  ArrowSeparateVertical,
  ArrowTlCircle,
  ArrowTlSquare,
  ArrowTrCircle,
  ArrowTrSquare,
  ArrowUnion,
  ArrowUnionVertical,
  ArrowUp,
  ArrowUpCircle,
  Asana,
  AtSign,
  AtSignCircle,
  Atom,
  Attachment,
  AugmentedReality,
  AutoFlash,
  AviFormat,
  Axes,
  Backward15Seconds,
  Bag,
  Bank,
  Barcode,
  Basketball,
  BasketballAlt,
  BasketballField,
  Battery25,
  Battery50,
  Battery75,
  BatteryCharging,
  BatteryEmpty,
  BatteryFull,
  BatteryIndicator,
  BatteryWarning,
  Bbq,
  BeachBag,
  BeachBagBig,
  Bed,
  BedReady,
  Behance,
  BehanceTag,
  Bell,
  BellNotification,
  BellOff,
  Bicycle,
  Bin,
  BinAdd,
  BinFull,
  BinHalf,
  BinMinus,
  Bishop,
  Bitbucket,
  Bluetooth,
  BluetoothTag,
  Bold,
  BoldSquare,
  Bonfire,
  Book,
  BookStack,
  BookmarkBook,
  BookmarkCircle,
  BookmarkEmpty,
  BorderBl,
  BorderBottom,
  BorderBr,
  BorderInner,
  BorderLeft,
  BorderOut,
  BorderRight,
  BorderTl,
  BorderTop,
  BorderTr,
  BounceLeft,
  BounceRight,
  BowlingBall,
  Box,
  BoxIso,
  BoxingGlove,
  Brain,
  BrainElectricity,
  BrainResearch,
  BrainWarning,
  BreadSlice,
  Brightness,
  BrightnessWindow,
  BubbleDownload,
  BubbleError,
  BubbleIncome,
  BubbleOutcome,
  BubbleSearch,
  BubbleStar,
  BubbleUpload,
  BubbleWarning,
  Building,
  Bus,
  BusStop,
  CableTag,
  Calculator,
  Calendar,
  Camera,
  Cancel,
  CandlestickChart,
  Car,
  Carbon,
  CardIssue,
  CardLocked,
  CardSecurity,
  CardWallet,
  Cart,
  CartAlt,
  Cash,
  Cell2X2,
  CenterAlign,
  ChatAdd,
  ChatBubble,
  ChatBubbleCheck,
  ChatBubbleCheck1,
  ChatBubbleEmpty,
  ChatBubbleError,
  ChatBubbleQuestion,
  ChatBubbleTranslate,
  ChatBubbleWarning,
  ChatLines,
  ChatRemove,
  Check,
  CheckCircle,
  CheckWindow,
  Chocolate,
  Chromecast,
  ChromecastActive,
  Church,
  ChurchAlt,
  CinemaOld,
  Circle,
  City,
  CleanWater,
  ClipboardCheck,
  Clock,
  ClosedCaptions,
  Closet,
  Cloud,
  CloudBookAlt,
  CloudCheck,
  CloudDesync,
  CloudDownload,
  CloudError,
  CloudSunny,
  CloudSync,
  CloudUpload,
  Clutery,
  Code,
  CodeBrackets,
  CodeBracketsSquare,
  Codepen,
  CoffeeCup,
  Coin,
  CollageFrame,
  Collapse,
  ColorFilter,
  ColorPicker,
  ColorPickerEmpty,
  Combine,
  CompactDisc,
  Compass,
  Compress,
  CompressLines,
  Computer,
  Consumable,
  ControlSlider,
  Cookie,
  Cooling,
  Copy,
  Copyright,
  CornerBottomLeft,
  CornerBottomRight,
  CornerTopLeft,
  CornerTopRight,
  Cpu,
  CpuWarning,
  CrackedEgg,
  CreativeCommons,
  CreditCard,
  CreditCards,
  Crib,
  Crop,
  CropRotateBl,
  CropRotateBr,
  CropRotateTl,
  CropRotateTr,
  Css3,
  CursorPointer,
  Cut,
  CutAlt,
  Cycling,
  Cylinder,
  DashFlag,
  Dashboard,
  DashboardDots,
  DashboardSpeed,
  DataTransferBoth,
  DataTransferCheck,
  DataTransferDown,
  DataTransferUp,
  DataTransferWarning,
  DatabaseBackup,
  DatabaseExport,
  DatabaseMonitor,
  DatabaseRestore,
  DatabaseScript,
  DatabaseSettings,
  DatabaseStar,
  DatabaseStats,
  DatabaseTag,
  Db,
  DbCheck,
  DbError,
  DbSearch,
  DbStar,
  DbWarning,
  DeCompress,
  DeleteCircle,
  Delivery,
  DeliveryTruck,
  Depth,
  DesignNib,
  DesignPencil,
  Desk,
  Dialpad,
  Diameter,
  DiceFive,
  DiceFour,
  DiceOne,
  DiceSix,
  DiceThree,
  DiceTwo,
  DimmerSwitch,
  DirectorChair,
  Discord,
  Dishwasher,
  Display4K,
  Divide,
  DivideSelection1,
  DivideSelection2,
  DivideThree,
  Dna,
  DocSearch,
  DocSearchAlt,
  DocStar,
  DocStarAlt,
  Dollar,
  DomoticIssue,
  Donate,
  DoubleCheck,
  DownRoundArrow,
  Download,
  DownloadCircle,
  DownloadDataWindow,
  DownloadSquare,
  Drag,
  DragHandGesture,
  Drawer,
  Dribbble,
  Drone,
  DroneChargeFull,
  DroneChargeHalf,
  DroneChargeLow,
  DroneCheck,
  DroneError,
  DroneLanding,
  DroneRefresh,
  DroneTakeOff,
  Droplet,
  DropletHalf,
  EaseCurveControlPoints,
  EaseIn,
  EaseInControlPoint,
  EaseInOut,
  EaseOut,
  EaseOutControlPoint,
  EcologyBook,
  Edit,
  EditPencil,
  Egg,
  Eject,
  ElectronicsChip,
  ElectronicsTransistor,
  Emoji,
  EmojiBall,
  EmojiBlinkLeft,
  EmojiBlinkRight,
  EmojiLookDown,
  EmojiLookLeft,
  EmojiLookRight,
  EmojiLookUp,
  EmojiPuzzled,
  EmojiQuite,
  EmojiReally,
  EmojiSad,
  EmojiSatisfied,
  EmojiSingLeft,
  EmojiSingLeftNote,
  EmojiSingRight,
  EmojiSingRightNote,
  EmojiSurprise,
  EmojiSurpriseAlt,
  EmojiTalkingAngry,
  EmojiTalkingHappy,
  EmojiThinkLeft,
  EmojiThinkRight,
  EmptyPage,
  EnergyUsageWindow,
  Enlarge,
  EnlargeRoundArrow,
  Erase,
  ErrorWindow,
  Euro,
  EuroSquare,
  EvCharge,
  EvChargeAlt,
  EvPlug,
  EvPlugCharging,
  EvPlugError,
  EvStation,
  EvTag,
  Exclude,
  Expand,
  ExpandLines,
  EyeAlt,
  EyeClose,
  EyeEmpty,
  EyeOff,
  FaceId,
  Facebook,
  FacebookTag,
  Facetime,
  Farm,
  FastArrowDown,
  FastArrowDownBox,
  FastArrowLeft,
  FastArrowLeftBox,
  FastArrowRight,
  FastArrowRightBox,
  FastArrowUp,
  FastArrowUpBox,
  FastDownCircle,
  FastLeftCircle,
  FastRightCircle,
  FastUpCircle,
  FavouriteBook,
  FavouriteWindow,
  Female,
  Figma,
  FileNotFound,
  Filter,
  FilterAlt,
  Finder,
  Fingerprint,
  FingerprintCheckCircle,
  FingerprintCircle,
  FingerprintErrorCircle,
  FingerprintLockCircle,
  FingerprintPhone,
  FingerprintScan,
  FingerprintSquare,
  FingerprintWindow,
  FireFlame,
  Fishing,
  Flare,
  Flash,
  FlashOff,
  Flask,
  Flip,
  FlipReverse,
  Flower,
  Fluorine,
  Fog,
  Folder,
  FolderAlert,
  FolderSettings,
  FontSize,
  Football,
  FootballBall,
  Forward,
  Forward15Seconds,
  ForwardMessage,
  Frame,
  FrameAlt,
  FrameAltEmpty,
  FrameSelect,
  FrameSimple,
  FrameTool,
  Fridge,
  Fx,
  FxTag,
  Gamepad,
  Garage,
  Gas,
  GasTank,
  GasTankDrop,
  GifFormat,
  Gift,
  GitBranch,
  GitCommand,
  GitCommit,
  GitCompare,
  GitFork,
  GitHub,
  GitLabFull,
  GitMerge,
  GitPullRequest,
  GithubCircle,
  GlassEmpty,
  GlassHalf,
  GlassHalfAlt,
  Glasses,
  Globe,
  Golf,
  Google,
  GoogleCircle,
  GoogleDocs,
  GoogleDrive,
  GoogleDriveCheck,
  GoogleDriveSync,
  GoogleDriveWarning,
  GoogleHome,
  GoogleOne,
  Gps,
  GraduationCap,
  GraphDown,
  GraphUp,
  GreenBus,
  GreenTruck,
  GreenVehicle,
  GridAdd,
  GridMinus,
  GridRemove,
  Group,
  Gym,
  HalfCookie,
  HalfMoon,
  Hammer,
  HandBrake,
  Handbag,
  HardDrive,
  Hat,
  Hd,
  HdDisplay,
  Hdr,
  Headset,
  HeadsetCharge,
  HeadsetHelp,
  HeadsetIssue,
  HealthShield,
  Healthcare,
  Heart,
  Heating,
  HeavyRain,
  HelpCircle,
  HelpSquare,
  Heptagon,
  HerSlips,
  Hexagon,
  HexagonAlt,
  HexagonDice,
  HighPriority,
  HistoricShield,
  HistoricShieldAlt,
  Home,
  HomeAlt,
  HomeAltSlim,
  HomeAltSlimHoriz,
  HomeHospital,
  HomeSale,
  HomeSecure,
  HomeShield,
  HomeSimple,
  HomeSimpleDoor,
  HomeTable,
  HomeUser,
  HorizDistributionLeft,
  HorizDistributionRight,
  HorizontalMerge,
  HorizontalSplit,
  Hospital,
  HospitalSign,
  HotAirBalloon,
  Hourglass,
  Html5,
  Hydrogen,
  Iconoir,
  Import,
  Inclination,
  Industry,
  Infinite,
  InfoEmpty,
  InputField,
  InputOutput,
  InputSearch,
  Instagram,
  Internet,
  Intersect,
  IntersectAlt,
  IosSettings,
  IpAddress,
  IrisScan,
  Italic,
  ItalicSquare,
  Journal,
  JournalPage,
  JpegFormat,
  JpgFormat,
  KanbanBoard,
  KeyAlt,
  KeyAltBack,
  KeyAltMinus,
  KeyAltPlus,
  KeyAltRemove,
  Keyframe,
  KeyframeAlignCenter,
  KeyframeAlignHorizontal,
  KeyframeAlignVertical,
  KeyframePosition,
  Keyframes,
  KeyframesCouple,
  Label,
  Lamp,
  Language,
  Laptop,
  LaptopCharging,
  LaptopFix,
  LaptopIssue,
  LargeSuitcase,
  LayoutLeft,
  LayoutRight,
  Leaderboard,
  LeaderboardStar,
  Leaf,
  LeftRoundArrow,
  Lens,
  Lifebelt,
  LightBulb,
  LightBulbOff,
  LightBulbOn,
  LineSpace,
  Linear,
  Link,
  LinkedIn,
  Linux,
  List,
  ListSelect,
  LoadActionFloppy,
  Lock,
  LockKey,
  LockedBook,
  LockedWindow,
  LogDenied,
  LogIn,
  LogOut,
  LongArrowDownLeft,
  LongArrowDownRight,
  LongArrowLeftDown,
  LongArrowLeftUp,
  LongArrowRightDown,
  LongArrowRightUp,
  LongArrowRightUp1,
  LongArrowUpLeft,
  LongArrowUpRight,
  LotOfCash,
  MacControlKey,
  MacDock,
  MacOptionKey,
  MacOsWindow,
  Magnet,
  MagnetEnergy,
  Mail,
  MailIn,
  MailOpened,
  MailOut,
  Male,
  Map,
  MapIssue,
  MapsArrow,
  MapsArrowDiagonal,
  MapsArrowIssue,
  MapsGoStraight,
  MapsTurnBack,
  MapsTurnLeft,
  MapsTurnRight,
  MaskSquare,
  MastercardCard,
  MathBook,
  Maximize,
  Medal,
  Medal1St,
  MediaImage,
  MediaImageFolder,
  MediaImageList,
  MediaVideo,
  MediaVideoFolder,
  MediaVideoList,
  Medium,
  Megaphone,
  Menu,
  MenuScale,
  Message,
  MessageAlert,
  MessageText,
  Metro,
  Mic,
  MicAdd,
  MicCheck,
  MicMute,
  MicRemove,
  MicSpeaking,
  MicWarning,
  Microscope,
  Minus,
  Minus1,
  MinusCircle,
  MinusHexagon,
  MinusPinAlt,
  MinusSquare,
  Mirror,
  MissingFont,
  ModernTv,
  ModernTv4K,
  MoneySquare,
  MoonSat,
  MoreHoriz,
  MoreHorizCircle,
  MoreVert,
  MoreVertCircle,
  Motorcycle,
  MouseButtonLeft,
  MouseButtonRight,
  MouseScrollWheel,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveRuler,
  MoveUp,
  Movie,
  MpegFormat,
  MultiBubble,
  MultiMacOsWindow,
  MultiWindow,
  MultiplePages,
  MultiplePagesAdd,
  MultiplePagesDelete,
  MultiplePagesEmpty,
  MultiplePagesRemove,
  MusicDoubleNote,
  MusicDoubleNoteAdd,
  MusicNote,
  MusicNoteAdd,
  NavArrowDown,
  NavArrowLeft,
  NavArrowRight,
  NavArrowUp,
  Navigator,
  NavigatorAlt,
  Network,
  NetworkAlt,
  NetworkLeft,
  NetworkRight,
  NewTab,
  NintendoSwitch,
  Nitrogen,
  NoAccessWindow,
  NoBattery,
  NoCoin,
  NoCreditCard,
  NoLink,
  NoLock,
  NoSmoking,
  NoSmokingCircle,
  Notes,
  Npm,
  NpmSquare,
  NumberedListLeft,
  NumberedListRight,
  Octagon,
  OffTag,
  OilIndustry,
  OnTag,
  OneFingerSelectHandGesture,
  OnePointCircle,
  OpenBook,
  OpenInBrowser,
  OpenInWindow,
  OpenNewWindow,
  OpenSelectHandGesture,
  OpenVpn,
  OrangeHalf,
  OrangeSlice,
  OrangeSliceAlt,
  OrganicFood,
  OrganicFoodSquare,
  OrthogonalView,
  Oxygen,
  Package,
  PackageLock,
  Packages,
  Pacman,
  Page,
  PageDown,
  PageEdit,
  PageFlip,
  PageLeft,
  PageRight,
  PageSearch,
  PageStar,
  PageUp,
  Palette,
  PanoramaEnlarge,
  PanoramaReduce,
  Pants,
  PantsAlt,
  Parking,
  PasswordCursor,
  PasswordError,
  PasswordPass,
  PasteClipboard,
  PathArrow,
  Pause,
  PauseWindow,
  Paypal,
  PcCheck,
  PcFirewall,
  PcMouse,
  PcNoEntry,
  PcWarning,
  PeaceHand,
  PenConnectBluetooth,
  PenConnectWifi,
  PenTablet,
  PenTabletConnectUsb,
  PenTabletConnectWifi,
  Pentagon,
  PeopleTag,
  Percentage,
  PercentageCircle,
  PercentageSquare,
  PerspectiveView,
  PharmacyCrossCircle,
  PharmacyCrossSquare,
  Phone,
  PhoneAdd,
  PhoneDelete,
  PhoneDisabled,
  PhoneIncome,
  PhoneOutcome,
  PhonePaused,
  PhoneRemove,
  PiggyBank,
  Pillow,
  Pin,
  PinAlt,
  PineTree,
  Pinterest,
  PizzaSlice,
  Planet,
  PlanetAlt,
  PlanetSat,
  Play,
  Playlist,
  PlaylistAdd,
  PlaylistPlay,
  PlaystationGamepad,
  PlugTypeA,
  PlugTypeC,
  PlugTypeG,
  PlugTypeL,
  Plus,
  PngFormat,
  Pocket,
  Podcast,
  Pokeball,
  Position,
  PositionAlign,
  Potion,
  Pound,
  PrecisionTool,
  Printer,
  PrinterAlt,
  PrintingPage,
  PriorityDown,
  PriorityUp,
  PrivateWifi,
  ProfileCircle,
  Prohibition,
  Puzzle,
  QrCode,
  QuestionMark,
  Quote,
  QuoteMessage,
  Radiation,
  Radius,
  Rain,
  RawFormat,
  ReceiveDollars,
  ReceiveEuros,
  ReceivePounds,
  ReceiveYens,
  Redo,
  RedoAction,
  RedoCircle,
  Reduce,
  ReduceRoundArrow,
  Refresh,
  RefreshCircular,
  RefreshDouble,
  ReloadWindow,
  ReminderHandGesture,
  RemoveDatabaseScript,
  RemoveFolder,
  RemoveFrame,
  RemoveFromCart,
  RemoveKeyframe,
  RemoveKeyframeAlt,
  RemoveKeyframes,
  RemoveLink,
  RemoveMediaImage,
  RemoveMediaVideo,
  RemovePage,
  RemovePageAlt,
  RemovePin,
  RemovePinAlt,
  RemoveSelection,
  RemoveSquare,
  RemoveUser,
  Repeat,
  RepeatOnce,
  Reply,
  ReplyToMessage,
  ReportColumns,
  Reports,
  Repository,
  Restart,
  Rewind,
  Rhombus,
  RightRoundArrow,
  Rings,
  Rocket,
  Rook,
  RotateCameraLeft,
  RotateCameraRight,
  RoundFlask,
  RoundedMirror,
  RssFeed,
  RssFeedTag,
  RubikCube,
  Ruler,
  RulerAdd,
  RulerCombine,
  RulerRemove,
  Running,
  Safari,
  Sandals,
  SaveActionFloppy,
  SaveFloppyDisk,
  ScaleFrameEnlarge,
  ScaleFrameReduce,
  ScanBarcode,
  ScanQrCode,
  Scanning,
  Scarf,
  Scissor,
  ScissorAlt,
  Screenshot,
  SeaAndSun,
  SeaWaves,
  Search,
  SearchEngine,
  SearchFont,
  SearchWindow,
  SecureWindow,
  SecurityPass,
  SelectWindow,
  Selection,
  SelectiveTool,
  Send,
  SendDiagonal,
  SendDollars,
  SendEuros,
  SendMail,
  SendPounds,
  SendYens,
  Server,
  ServerConnection,
  Settings,
  SettingsCloud,
  SettingsProfiles,
  ShareAndroid,
  ShareIos,
  Shield,
  ShieldAdd,
  ShieldAlert,
  ShieldAlt,
  ShieldBroken,
  ShieldCheck,
  ShieldCross,
  ShieldDownload,
  ShieldEye,
  ShieldLoading,
  ShieldMinus,
  ShieldQuestion,
  ShieldSearch,
  ShieldUpload,
  Shop,
  ShopAlt,
  ShoppingBag,
  ShoppingBagAdd,
  ShoppingBagAlt,
  ShoppingBagArrowDown,
  ShoppingBagArrowUp,
  ShoppingBagCheck,
  ShoppingBagIssue,
  ShoppingBagRemove,
  ShoppingCode,
  ShoppingCodeCheck,
  ShoppingCodeError,
  ShortPants,
  ShortPantsAlt,
  Shortcut,
  Shuffle,
  SidebarCollapse,
  SidebarExpand,
  SigmaFunction,
  SimpleCart,
  SingleTapGesture,
  Skateboard,
  Skateboarding,
  SkipNext,
  SkipPrev,
  SleeperChair,
  SmallLamp,
  SmallLampAlt,
  SmallShop,
  SmallShopAlt,
  SmartphoneDevice,
  Smoking,
  Snapchat,
  Snow,
  SnowFlake,
  Soap,
  SoccerBall,
  Sofa,
  Soil,
  SoilAlt,
  Sort,
  SortDown,
  SortUp,
  SoundHigh,
  SoundLow,
  SoundMin,
  SoundOff,
  Spades,
  Sphere,
  Spiral,
  SpockHandGesture,
  Square,
  Stackoverflow,
  Star,
  StarDashed,
  StarHalfDashed,
  StatDown,
  StatUp,
  StatsDownSquare,
  StatsReport,
  StatsUpSquare,
  Stretching,
  Stroller,
  StyleBorder,
  SubmitDocument,
  Substract,
  Suggestion,
  SunLight,
  Svg3DAddHole,
  Svg3DArc,
  Svg3DArcCenterPt,
  Svg3DBridge,
  Svg3DCenterBox,
  Svg3DEllipse,
  Svg3DEllipseThreePts,
  Svg3DPtBox,
  Svg3DRectCornerToCorner,
  Svg3DRectFromCenter,
  Svg3DRectThreePts,
  Svg3DSelectEdge,
  Svg3DSelectFace,
  Svg3DSelectPoint,
  Svg3DSelectSolid,
  Svg3DThreePtsBox,
  SvgFormat,
  Swimming,
  SwipeDownGesture,
  SwipeLeftGesture,
  SwipeRightGesture,
  SwipeTwoFingersDownGesture,
  SwipeTwoFingersLeftGesture,
  SwipeTwoFingersRightGesture,
  SwipeTwoFingersUpGesture,
  SwipeUpGesture,
  SwitchOff,
  SwitchOn,
  SystemRestart,
  SystemShut,
  Table,
  Table2Columns,
  TableRows,
  TaskList,
  Telegram,
  TelegramCircle,
  TennisBall,
  TennisBallAlt,
  Terminal,
  TerminalTag,
  TestTube,
  Text,
  TextAlt,
  TextBox,
  TextSize,
  ThreePointsCircle,
  ThreeStars,
  ThumbsDown,
  ThumbsUp,
  Thunderstorm,
  TifFormat,
  TiffFormat,
  TikTok,
  Timer,
  TimerOff,
  Tools,
  Tournament,
  Tower,
  TowerCheck,
  TowerNoAccess,
  TowerWarning,
  Trademark,
  Train,
  Tram,
  TransitionDown,
  TransitionLeft,
  TransitionRight,
  TransitionUp,
  Translate,
  Trash,
  Treadmill,
  Tree,
  Trekking,
  Trello,
  Triangle,
  TriangleFlag,
  TriangleFlagCircle,
  TriangleFlagTwoStripes,
  Trophy,
  Truck,
  TruckLength,
  Tunnel,
  Tv,
  TvFix,
  TvIssue,
  Twitter,
  TwitterVerifiedBadge,
  TwoPointsCircle,
  TwoSeaterSofa,
  Type,
  UmbrellaFull,
  Underline,
  UnderlineSquare,
  Undo,
  UndoAction,
  UndoCircle,
  Union,
  UnionAlt,
  UnionHorizAlt,
  Unity,
  Unity5,
  UpRoundArrow,
  Upload,
  UploadDataWindow,
  UploadSquare,
  Usb,
  User,
  UserBag,
  UserCart,
  UserCircle,
  UserScan,
  UserSquare,
  Vegan,
  VeganCircle,
  VeganSquare,
  VerifiedBadge,
  VerifiedUser,
  VerticalMerge,
  VerticalSplit,
  Vials,
  VideoCamera,
  VideoCameraOff,
  View360,
  ViewColumns2,
  ViewColumns3,
  ViewGrid,
  ViewStructureDown,
  ViewStructureUp,
  Voice,
  VoiceCircle,
  VoiceError,
  VoiceLockCircle,
  VoiceOk,
  VoicePhone,
  VoiceScan,
  VoiceSquare,
  VrSymbol,
  Waist,
  Walking,
  Wallet,
  WarningCircle,
  WarningHexagon,
  WarningSquare,
  WarningTriangle,
  WarningWindow,
  Wash,
  WashingMachine,
  WateringSoil,
  WebWindow,
  WebWindowClose,
  WebWindowEnergyConsumption,
  WebpFormat,
  Weight,
  WeightAlt,
  WhiteFlag,
  Wifi,
  WifiError,
  WifiIssue,
  WifiOff,
  WifiSignalNone,
  WifiTag,
  Wind,
  Windows,
  WrapText,
  Wrench,
  Wristwatch,
  Www,
  XCoordinate,
  XboxA,
  XboxB,
  XboxX,
  XboxY,
  XrayView,
  YCoordinate,
  Yen,
  YenSquare,
  Yoga,
  YouTube,
  ZCoordinate,
  ZoomIn,
  ZoomOut,
} from "iconoir-react";

export const iconsLibrary: { [key: string]: any } = {
  Svg3DAddHole: Svg3DAddHole,
  Svg3DArcCenterPt: Svg3DArcCenterPt,
  Svg3DArc: Svg3DArc,
  Svg3DBridge: Svg3DBridge,
  Svg3DCenterBox: Svg3DCenterBox,
  Svg3DEllipseThreePts: Svg3DEllipseThreePts,
  Svg3DEllipse: Svg3DEllipse,
  Svg3DPtBox: Svg3DPtBox,
  Svg3DRectCornerToCorner: Svg3DRectCornerToCorner,
  Svg3DRectFromCenter: Svg3DRectFromCenter,
  Svg3DRectThreePts: Svg3DRectThreePts,
  Svg3DSelectEdge: Svg3DSelectEdge,
  Svg3DSelectFace: Svg3DSelectFace,
  Svg3DSelectPoint: Svg3DSelectPoint,
  Svg3DSelectSolid: Svg3DSelectSolid,
  Svg3DThreePtsBox: Svg3DThreePtsBox,
  AccessibilitySign: AccessibilitySign,
  AccessibilityTech: AccessibilityTech,
  Accessibility: Accessibility,
  Activity: Activity,
  AddCircle: AddCircle,
  AddDatabaseScript: AddDatabaseScript,
  AddFolder: AddFolder,
  AddFrame: AddFrame,
  AddHexagon: AddHexagon,
  AddKeyframeAlt: AddKeyframeAlt,
  AddKeyframe: AddKeyframe,
  AddKeyframes: AddKeyframes,
  AddLens: AddLens,
  AddMediaImage: AddMediaImage,
  AddMediaVideo: AddMediaVideo,
  AddPageAlt: AddPageAlt,
  AddPage: AddPage,
  AddPinAlt: AddPinAlt,
  AddSelection: AddSelection,
  AddSquare: AddSquare,
  AddToCart: AddToCart,
  AddUser: AddUser,
  AfricanTree: AfricanTree,
  AirConditioner: AirConditioner,
  AirplaneHelix45Deg: AirplaneHelix45Deg,
  AirplaneHelix: AirplaneHelix,
  AirplaneOff: AirplaneOff,
  AirplaneRotation: AirplaneRotation,
  Airplane: Airplane,
  Airplay: Airplay,
  Alarm: Alarm,
  AlbumCarousel: AlbumCarousel,
  AlbumList: AlbumList,
  AlbumOpen: AlbumOpen,
  Album: Album,
  AlignBottomBox: AlignBottomBox,
  AlignCenter: AlignCenter,
  AlignJustify: AlignJustify,
  AlignLeftBox: AlignLeftBox,
  AlignLeft: AlignLeft,
  AlignRightBox: AlignRightBox,
  AlignRight: AlignRight,
  AlignTopBox: AlignTopBox,
  AngleTool: AngleTool,
  AntennaOff: AntennaOff,
  AntennaSignalTag: AntennaSignalTag,
  AntennaSignal: AntennaSignal,
  Antenna: Antenna,
  AppNotification: AppNotification,
  AppWindow: AppWindow,
  AppleHalfAlt: AppleHalfAlt,
  AppleHalf: AppleHalf,
  AppleImac2021Side: AppleImac2021Side,
  AppleImac2021: AppleImac2021,
  AppleMac: AppleMac,
  AppleSwift: AppleSwift,
  AppleWallet: AppleWallet,
  Apple: Apple,
  ArSymbol: ArSymbol,
  Arcade: Arcade,
  ArcheryMatch: ArcheryMatch,
  Archery: Archery,
  Archive: Archive,
  AreaSearch: AreaSearch,
  ArrowArchery: ArrowArchery,
  ArrowBlCircle: ArrowBlCircle,
  ArrowBlSquare: ArrowBlSquare,
  ArrowBrCircle: ArrowBrCircle,
  ArrowBrSquare: ArrowBrSquare,
  ArrowDownCircle: ArrowDownCircle,
  ArrowDown: ArrowDown,
  ArrowEmailForward: ArrowEmailForward,
  ArrowLeftCircle: ArrowLeftCircle,
  ArrowLeft: ArrowLeft,
  ArrowRightCircle: ArrowRightCircle,
  ArrowRight: ArrowRight,
  ArrowSeparateVertical: ArrowSeparateVertical,
  ArrowSeparate: ArrowSeparate,
  ArrowTlCircle: ArrowTlCircle,
  ArrowTlSquare: ArrowTlSquare,
  ArrowTrCircle: ArrowTrCircle,
  ArrowTrSquare: ArrowTrSquare,
  ArrowUnionVertical: ArrowUnionVertical,
  ArrowUnion: ArrowUnion,
  ArrowUpCircle: ArrowUpCircle,
  ArrowUp: ArrowUp,
  Asana: Asana,
  AtSignCircle: AtSignCircle,
  AtSign: AtSign,
  Atom: Atom,
  Attachment: Attachment,
  AugmentedReality: AugmentedReality,
  AutoFlash: AutoFlash,
  AviFormat: AviFormat,
  Axes: Axes,
  Backward15Seconds: Backward15Seconds,
  Bag: Bag,
  Bank: Bank,
  Barcode: Barcode,
  BasketballAlt: BasketballAlt,
  BasketballField: BasketballField,
  Basketball: Basketball,
  Battery25: Battery25,
  Battery50: Battery50,
  Battery75: Battery75,
  BatteryCharging: BatteryCharging,
  BatteryEmpty: BatteryEmpty,
  BatteryFull: BatteryFull,
  BatteryIndicator: BatteryIndicator,
  BatteryWarning: BatteryWarning,
  Bbq: Bbq,
  BeachBagBig: BeachBagBig,
  BeachBag: BeachBag,
  BedReady: BedReady,
  Bed: Bed,
  BehanceTag: BehanceTag,
  Behance: Behance,
  BellNotification: BellNotification,
  BellOff: BellOff,
  Bell: Bell,
  Bicycle: Bicycle,
  BinAdd: BinAdd,
  BinFull: BinFull,
  BinHalf: BinHalf,
  BinMinus: BinMinus,
  Bin: Bin,
  Bishop: Bishop,
  Bitbucket: Bitbucket,
  BluetoothTag: BluetoothTag,
  Bluetooth: Bluetooth,
  BoldSquare: BoldSquare,
  Bold: Bold,
  Bonfire: Bonfire,
  BookStack: BookStack,
  Book: Book,
  BookmarkBook: BookmarkBook,
  BookmarkCircle: BookmarkCircle,
  BookmarkEmpty: BookmarkEmpty,
  BorderBl: BorderBl,
  BorderBottom: BorderBottom,
  BorderBr: BorderBr,
  BorderInner: BorderInner,
  BorderLeft: BorderLeft,
  BorderOut: BorderOut,
  BorderRight: BorderRight,
  BorderTl: BorderTl,
  BorderTop: BorderTop,
  BorderTr: BorderTr,
  BounceLeft: BounceLeft,
  BounceRight: BounceRight,
  BowlingBall: BowlingBall,
  BoxIso: BoxIso,
  Box: Box,
  BoxingGlove: BoxingGlove,
  BrainElectricity: BrainElectricity,
  BrainResearch: BrainResearch,
  BrainWarning: BrainWarning,
  Brain: Brain,
  BreadSlice: BreadSlice,
  BrightnessWindow: BrightnessWindow,
  Brightness: Brightness,
  BubbleDownload: BubbleDownload,
  BubbleError: BubbleError,
  BubbleIncome: BubbleIncome,
  BubbleOutcome: BubbleOutcome,
  BubbleSearch: BubbleSearch,
  BubbleStar: BubbleStar,
  BubbleUpload: BubbleUpload,
  BubbleWarning: BubbleWarning,
  Building: Building,
  BusStop: BusStop,
  Bus: Bus,
  CableTag: CableTag,
  Calculator: Calculator,
  Calendar: Calendar,
  Camera: Camera,
  Cancel: Cancel,
  CandlestickChart: CandlestickChart,
  Car: Car,
  Carbon: Carbon,
  CardIssue: CardIssue,
  CardLocked: CardLocked,
  CardSecurity: CardSecurity,
  CardWallet: CardWallet,
  CartAlt: CartAlt,
  Cart: Cart,
  Cash: Cash,
  Cell2X2: Cell2X2,
  CenterAlign: CenterAlign,
  ChatAdd: ChatAdd,
  ChatBubbleCheck1: ChatBubbleCheck1,
  ChatBubbleCheck: ChatBubbleCheck,
  ChatBubbleEmpty: ChatBubbleEmpty,
  ChatBubbleError: ChatBubbleError,
  ChatBubbleQuestion: ChatBubbleQuestion,
  ChatBubbleTranslate: ChatBubbleTranslate,
  ChatBubbleWarning: ChatBubbleWarning,
  ChatBubble: ChatBubble,
  ChatLines: ChatLines,
  ChatRemove: ChatRemove,
  CheckCircle: CheckCircle,
  CheckWindow: CheckWindow,
  Check: Check,
  Chocolate: Chocolate,
  ChromecastActive: ChromecastActive,
  Chromecast: Chromecast,
  ChurchAlt: ChurchAlt,
  Church: Church,
  CinemaOld: CinemaOld,
  Circle: Circle,
  City: City,
  CleanWater: CleanWater,
  ClipboardCheck: ClipboardCheck,
  Clock: Clock,
  ClosedCaptions: ClosedCaptions,
  Closet: Closet,
  CloudBookAlt: CloudBookAlt,
  CloudCheck: CloudCheck,
  CloudDesync: CloudDesync,
  CloudDownload: CloudDownload,
  CloudError: CloudError,
  CloudSunny: CloudSunny,
  CloudSync: CloudSync,
  CloudUpload: CloudUpload,
  Cloud: Cloud,
  Clutery: Clutery,
  CodeBracketsSquare: CodeBracketsSquare,
  CodeBrackets: CodeBrackets,
  Code: Code,
  Codepen: Codepen,
  CoffeeCup: CoffeeCup,
  Coin: Coin,
  CollageFrame: CollageFrame,
  Collapse: Collapse,
  ColorFilter: ColorFilter,
  ColorPickerEmpty: ColorPickerEmpty,
  ColorPicker: ColorPicker,
  Combine: Combine,
  CompactDisc: CompactDisc,
  Compass: Compass,
  CompressLines: CompressLines,
  Compress: Compress,
  Computer: Computer,
  Consumable: Consumable,
  ControlSlider: ControlSlider,
  Cookie: Cookie,
  Cooling: Cooling,
  Copy: Copy,
  Copyright: Copyright,
  CornerBottomLeft: CornerBottomLeft,
  CornerBottomRight: CornerBottomRight,
  CornerTopLeft: CornerTopLeft,
  CornerTopRight: CornerTopRight,
  CpuWarning: CpuWarning,
  Cpu: Cpu,
  CrackedEgg: CrackedEgg,
  CreativeCommons: CreativeCommons,
  CreditCard: CreditCard,
  CreditCards: CreditCards,
  Crib: Crib,
  CropRotateBl: CropRotateBl,
  CropRotateBr: CropRotateBr,
  CropRotateTl: CropRotateTl,
  CropRotateTr: CropRotateTr,
  Crop: Crop,
  Css3: Css3,
  CursorPointer: CursorPointer,
  CutAlt: CutAlt,
  Cut: Cut,
  Cycling: Cycling,
  Cylinder: Cylinder,
  DashFlag: DashFlag,
  DashboardDots: DashboardDots,
  DashboardSpeed: DashboardSpeed,
  Dashboard: Dashboard,
  DataTransferBoth: DataTransferBoth,
  DataTransferCheck: DataTransferCheck,
  DataTransferDown: DataTransferDown,
  DataTransferUp: DataTransferUp,
  DataTransferWarning: DataTransferWarning,
  DatabaseBackup: DatabaseBackup,
  DatabaseExport: DatabaseExport,
  DatabaseMonitor: DatabaseMonitor,
  DatabaseRestore: DatabaseRestore,
  DatabaseScript: DatabaseScript,
  DatabaseSettings: DatabaseSettings,
  DatabaseStar: DatabaseStar,
  DatabaseStats: DatabaseStats,
  DatabaseTag: DatabaseTag,
  DbCheck: DbCheck,
  DbError: DbError,
  DbSearch: DbSearch,
  DbStar: DbStar,
  DbWarning: DbWarning,
  Db: Db,
  DeCompress: DeCompress,
  DeleteCircle: DeleteCircle,
  DeliveryTruck: DeliveryTruck,
  Delivery: Delivery,
  Depth: Depth,
  DesignNib: DesignNib,
  DesignPencil: DesignPencil,
  Desk: Desk,
  Dialpad: Dialpad,
  Diameter: Diameter,
  DiceFive: DiceFive,
  DiceFour: DiceFour,
  DiceOne: DiceOne,
  DiceSix: DiceSix,
  DiceThree: DiceThree,
  DiceTwo: DiceTwo,
  DimmerSwitch: DimmerSwitch,
  DirectorChair: DirectorChair,
  Discord: Discord,
  Dishwasher: Dishwasher,
  Display4K: Display4K,
  DivideSelection1: DivideSelection1,
  DivideSelection2: DivideSelection2,
  DivideThree: DivideThree,
  Divide: Divide,
  Dna: Dna,
  DocSearchAlt: DocSearchAlt,
  DocSearch: DocSearch,
  DocStarAlt: DocStarAlt,
  DocStar: DocStar,
  Dollar: Dollar,
  DomoticIssue: DomoticIssue,
  Donate: Donate,
  DoubleCheck: DoubleCheck,
  DownRoundArrow: DownRoundArrow,
  DownloadCircle: DownloadCircle,
  DownloadDataWindow: DownloadDataWindow,
  DownloadSquare: DownloadSquare,
  Download: Download,
  DragHandGesture: DragHandGesture,
  Drag: Drag,
  Drawer: Drawer,
  Dribbble: Dribbble,
  DroneChargeFull: DroneChargeFull,
  DroneChargeHalf: DroneChargeHalf,
  DroneChargeLow: DroneChargeLow,
  DroneCheck: DroneCheck,
  DroneError: DroneError,
  DroneLanding: DroneLanding,
  DroneRefresh: DroneRefresh,
  DroneTakeOff: DroneTakeOff,
  Drone: Drone,
  DropletHalf: DropletHalf,
  Droplet: Droplet,
  EaseCurveControlPoints: EaseCurveControlPoints,
  EaseInControlPoint: EaseInControlPoint,
  EaseInOut: EaseInOut,
  EaseIn: EaseIn,
  EaseOutControlPoint: EaseOutControlPoint,
  EaseOut: EaseOut,
  EcologyBook: EcologyBook,
  EditPencil: EditPencil,
  Edit: Edit,
  Egg: Egg,
  Eject: Eject,
  ElectronicsChip: ElectronicsChip,
  ElectronicsTransistor: ElectronicsTransistor,
  EmojiBall: EmojiBall,
  EmojiBlinkLeft: EmojiBlinkLeft,
  EmojiBlinkRight: EmojiBlinkRight,
  EmojiLookDown: EmojiLookDown,
  EmojiLookLeft: EmojiLookLeft,
  EmojiLookRight: EmojiLookRight,
  EmojiLookUp: EmojiLookUp,
  EmojiPuzzled: EmojiPuzzled,
  EmojiQuite: EmojiQuite,
  EmojiReally: EmojiReally,
  EmojiSad: EmojiSad,
  EmojiSatisfied: EmojiSatisfied,
  EmojiSingLeftNote: EmojiSingLeftNote,
  EmojiSingLeft: EmojiSingLeft,
  EmojiSingRightNote: EmojiSingRightNote,
  EmojiSingRight: EmojiSingRight,
  EmojiSurpriseAlt: EmojiSurpriseAlt,
  EmojiSurprise: EmojiSurprise,
  EmojiTalkingAngry: EmojiTalkingAngry,
  EmojiTalkingHappy: EmojiTalkingHappy,
  EmojiThinkLeft: EmojiThinkLeft,
  EmojiThinkRight: EmojiThinkRight,
  Emoji: Emoji,
  EmptyPage: EmptyPage,
  EnergyUsageWindow: EnergyUsageWindow,
  EnlargeRoundArrow: EnlargeRoundArrow,
  Enlarge: Enlarge,
  Erase: Erase,
  ErrorWindow: ErrorWindow,
  EuroSquare: EuroSquare,
  Euro: Euro,
  EvChargeAlt: EvChargeAlt,
  EvCharge: EvCharge,
  EvPlugCharging: EvPlugCharging,
  EvPlugError: EvPlugError,
  EvPlug: EvPlug,
  EvStation: EvStation,
  EvTag: EvTag,
  Exclude: Exclude,
  ExpandLines: ExpandLines,
  Expand: Expand,
  EyeAlt: EyeAlt,
  EyeClose: EyeClose,
  EyeEmpty: EyeEmpty,
  EyeOff: EyeOff,
  FaceId: FaceId,
  FacebookTag: FacebookTag,
  Facebook: Facebook,
  Facetime: Facetime,
  Farm: Farm,
  FastArrowDownBox: FastArrowDownBox,
  FastArrowDown: FastArrowDown,
  FastArrowLeftBox: FastArrowLeftBox,
  FastArrowLeft: FastArrowLeft,
  FastArrowRightBox: FastArrowRightBox,
  FastArrowRight: FastArrowRight,
  FastArrowUpBox: FastArrowUpBox,
  FastArrowUp: FastArrowUp,
  FastDownCircle: FastDownCircle,
  FastLeftCircle: FastLeftCircle,
  FastRightCircle: FastRightCircle,
  FastUpCircle: FastUpCircle,
  FavouriteBook: FavouriteBook,
  FavouriteWindow: FavouriteWindow,
  Female: Female,
  Figma: Figma,
  FileNotFound: FileNotFound,
  FilterAlt: FilterAlt,
  Filter: Filter,
  Finder: Finder,
  FingerprintCheckCircle: FingerprintCheckCircle,
  FingerprintCircle: FingerprintCircle,
  FingerprintErrorCircle: FingerprintErrorCircle,
  FingerprintLockCircle: FingerprintLockCircle,
  FingerprintPhone: FingerprintPhone,
  FingerprintScan: FingerprintScan,
  FingerprintSquare: FingerprintSquare,
  FingerprintWindow: FingerprintWindow,
  Fingerprint: Fingerprint,
  FireFlame: FireFlame,
  Fishing: Fishing,
  Flare: Flare,
  FlashOff: FlashOff,
  Flash: Flash,
  Flask: Flask,
  FlipReverse: FlipReverse,
  Flip: Flip,
  Flower: Flower,
  Fluorine: Fluorine,
  Fog: Fog,
  FolderAlert: FolderAlert,
  FolderSettings: FolderSettings,
  Folder: Folder,
  FontSize: FontSize,
  FootballBall: FootballBall,
  Football: Football,
  Forward15Seconds: Forward15Seconds,
  ForwardMessage: ForwardMessage,
  Forward: Forward,
  FrameAltEmpty: FrameAltEmpty,
  FrameAlt: FrameAlt,
  FrameSelect: FrameSelect,
  FrameSimple: FrameSimple,
  FrameTool: FrameTool,
  Frame: Frame,
  Fridge: Fridge,
  FxTag: FxTag,
  Fx: Fx,
  Gamepad: Gamepad,
  Garage: Garage,
  GasTankDrop: GasTankDrop,
  GasTank: GasTank,
  Gas: Gas,
  GifFormat: GifFormat,
  Gift: Gift,
  GitBranch: GitBranch,
  GitCommand: GitCommand,
  GitCommit: GitCommit,
  GitCompare: GitCompare,
  GitFork: GitFork,
  GitMerge: GitMerge,
  GitPullRequest: GitPullRequest,
  GitHub: GitHub,
  GitLabFull: GitLabFull,
  GithubCircle: GithubCircle,
  GlassEmpty: GlassEmpty,
  GlassHalfAlt: GlassHalfAlt,
  GlassHalf: GlassHalf,
  Glasses: Glasses,
  Globe: Globe,
  Golf: Golf,
  GoogleCircle: GoogleCircle,
  GoogleDocs: GoogleDocs,
  GoogleDriveCheck: GoogleDriveCheck,
  GoogleDriveSync: GoogleDriveSync,
  GoogleDriveWarning: GoogleDriveWarning,
  GoogleDrive: GoogleDrive,
  GoogleHome: GoogleHome,
  GoogleOne: GoogleOne,
  Google: Google,
  Gps: Gps,
  GraduationCap: GraduationCap,
  GraphDown: GraphDown,
  GraphUp: GraphUp,
  GreenBus: GreenBus,
  GreenTruck: GreenTruck,
  GreenVehicle: GreenVehicle,
  GridAdd: GridAdd,
  GridMinus: GridMinus,
  GridRemove: GridRemove,
  Group: Group,
  Gym: Gym,
  HalfCookie: HalfCookie,
  HalfMoon: HalfMoon,
  Hammer: Hammer,
  HandBrake: HandBrake,
  Handbag: Handbag,
  HardDrive: HardDrive,
  Hat: Hat,
  HdDisplay: HdDisplay,
  Hd: Hd,
  Hdr: Hdr,
  HeadsetCharge: HeadsetCharge,
  HeadsetHelp: HeadsetHelp,
  HeadsetIssue: HeadsetIssue,
  Headset: Headset,
  HealthShield: HealthShield,
  Healthcare: Healthcare,
  Heart: Heart,
  Heating: Heating,
  HeavyRain: HeavyRain,
  HelpCircle: HelpCircle,
  HelpSquare: HelpSquare,
  Heptagon: Heptagon,
  HerSlips: HerSlips,
  HexagonAlt: HexagonAlt,
  HexagonDice: HexagonDice,
  Hexagon: Hexagon,
  HighPriority: HighPriority,
  HistoricShieldAlt: HistoricShieldAlt,
  HistoricShield: HistoricShield,
  HomeAltSlimHoriz: HomeAltSlimHoriz,
  HomeAltSlim: HomeAltSlim,
  HomeAlt: HomeAlt,
  HomeHospital: HomeHospital,
  HomeSale: HomeSale,
  HomeSecure: HomeSecure,
  HomeShield: HomeShield,
  HomeSimpleDoor: HomeSimpleDoor,
  HomeSimple: HomeSimple,
  HomeTable: HomeTable,
  HomeUser: HomeUser,
  Home: Home,
  HorizDistributionLeft: HorizDistributionLeft,
  HorizDistributionRight: HorizDistributionRight,
  HorizontalMerge: HorizontalMerge,
  HorizontalSplit: HorizontalSplit,
  HospitalSign: HospitalSign,
  Hospital: Hospital,
  HotAirBalloon: HotAirBalloon,
  Hourglass: Hourglass,
  Html5: Html5,
  Hydrogen: Hydrogen,
  Iconoir: Iconoir,
  Import: Import,
  Inclination: Inclination,
  Industry: Industry,
  Infinite: Infinite,
  InfoEmpty: InfoEmpty,
  InputField: InputField,
  InputOutput: InputOutput,
  InputSearch: InputSearch,
  Instagram: Instagram,
  Internet: Internet,
  IntersectAlt: IntersectAlt,
  Intersect: Intersect,
  IosSettings: IosSettings,
  IpAddress: IpAddress,
  IrisScan: IrisScan,
  ItalicSquare: ItalicSquare,
  Italic: Italic,
  JournalPage: JournalPage,
  Journal: Journal,
  JpegFormat: JpegFormat,
  JpgFormat: JpgFormat,
  KanbanBoard: KanbanBoard,
  KeyAltBack: KeyAltBack,
  KeyAltMinus: KeyAltMinus,
  KeyAltPlus: KeyAltPlus,
  KeyAltRemove: KeyAltRemove,
  KeyAlt: KeyAlt,
  KeyframeAlignCenter: KeyframeAlignCenter,
  KeyframeAlignHorizontal: KeyframeAlignHorizontal,
  KeyframeAlignVertical: KeyframeAlignVertical,
  KeyframePosition: KeyframePosition,
  Keyframe: Keyframe,
  KeyframesCouple: KeyframesCouple,
  Keyframes: Keyframes,
  Label: Label,
  Lamp: Lamp,
  Language: Language,
  LaptopCharging: LaptopCharging,
  LaptopFix: LaptopFix,
  LaptopIssue: LaptopIssue,
  Laptop: Laptop,
  LargeSuitcase: LargeSuitcase,
  LayoutLeft: LayoutLeft,
  LayoutRight: LayoutRight,
  LeaderboardStar: LeaderboardStar,
  Leaderboard: Leaderboard,
  Leaf: Leaf,
  LeftRoundArrow: LeftRoundArrow,
  Lens: Lens,
  Lifebelt: Lifebelt,
  LightBulbOff: LightBulbOff,
  LightBulbOn: LightBulbOn,
  LightBulb: LightBulb,
  LineSpace: LineSpace,
  Linear: Linear,
  Link: Link,
  LinkedIn: LinkedIn,
  Linux: Linux,
  ListSelect: ListSelect,
  List: List,
  LoadActionFloppy: LoadActionFloppy,
  LockKey: LockKey,
  Lock: Lock,
  LockedBook: LockedBook,
  LockedWindow: LockedWindow,
  LogDenied: LogDenied,
  LogIn: LogIn,
  LogOut: LogOut,
  LongArrowDownLeft: LongArrowDownLeft,
  LongArrowDownRight: LongArrowDownRight,
  LongArrowLeftDown: LongArrowLeftDown,
  LongArrowLeftUp: LongArrowLeftUp,
  LongArrowRightDown: LongArrowRightDown,
  LongArrowRightUp1: LongArrowRightUp1,
  LongArrowRightUp: LongArrowRightUp,
  LongArrowUpLeft: LongArrowUpLeft,
  LongArrowUpRight: LongArrowUpRight,
  LotOfCash: LotOfCash,
  MacControlKey: MacControlKey,
  MacDock: MacDock,
  MacOptionKey: MacOptionKey,
  MacOsWindow: MacOsWindow,
  MagnetEnergy: MagnetEnergy,
  Magnet: Magnet,
  MailIn: MailIn,
  MailOpened: MailOpened,
  MailOut: MailOut,
  Mail: Mail,
  Male: Male,
  MapIssue: MapIssue,
  Map: Map,
  MapsArrowDiagonal: MapsArrowDiagonal,
  MapsArrowIssue: MapsArrowIssue,
  MapsArrow: MapsArrow,
  MapsGoStraight: MapsGoStraight,
  MapsTurnBack: MapsTurnBack,
  MapsTurnLeft: MapsTurnLeft,
  MapsTurnRight: MapsTurnRight,
  MaskSquare: MaskSquare,
  MastercardCard: MastercardCard,
  MathBook: MathBook,
  Maximize: Maximize,
  Medal1St: Medal1St,
  Medal: Medal,
  MediaImageFolder: MediaImageFolder,
  MediaImageList: MediaImageList,
  MediaImage: MediaImage,
  MediaVideoFolder: MediaVideoFolder,
  MediaVideoList: MediaVideoList,
  MediaVideo: MediaVideo,
  Medium: Medium,
  Megaphone: Megaphone,
  MenuScale: MenuScale,
  Menu: Menu,
  MessageAlert: MessageAlert,
  MessageText: MessageText,
  Message: Message,
  Metro: Metro,
  MicAdd: MicAdd,
  MicCheck: MicCheck,
  MicMute: MicMute,
  MicRemove: MicRemove,
  MicSpeaking: MicSpeaking,
  MicWarning: MicWarning,
  Mic: Mic,
  Microscope: Microscope,
  Minus1: Minus1,
  MinusCircle: MinusCircle,
  MinusHexagon: MinusHexagon,
  MinusPinAlt: MinusPinAlt,
  MinusSquare: MinusSquare,
  Minus: Minus,
  Mirror: Mirror,
  MissingFont: MissingFont,
  ModernTv4K: ModernTv4K,
  ModernTv: ModernTv,
  MoneySquare: MoneySquare,
  MoonSat: MoonSat,
  MoreHorizCircle: MoreHorizCircle,
  MoreHoriz: MoreHoriz,
  MoreVertCircle: MoreVertCircle,
  MoreVert: MoreVert,
  Motorcycle: Motorcycle,
  MouseButtonLeft: MouseButtonLeft,
  MouseButtonRight: MouseButtonRight,
  MouseScrollWheel: MouseScrollWheel,
  MoveDown: MoveDown,
  MoveLeft: MoveLeft,
  MoveRight: MoveRight,
  MoveRuler: MoveRuler,
  MoveUp: MoveUp,
  Movie: Movie,
  MpegFormat: MpegFormat,
  MultiBubble: MultiBubble,
  MultiMacOsWindow: MultiMacOsWindow,
  MultiWindow: MultiWindow,
  MultiplePagesAdd: MultiplePagesAdd,
  MultiplePagesDelete: MultiplePagesDelete,
  MultiplePagesEmpty: MultiplePagesEmpty,
  MultiplePagesRemove: MultiplePagesRemove,
  MultiplePages: MultiplePages,
  MusicDoubleNoteAdd: MusicDoubleNoteAdd,
  MusicDoubleNote: MusicDoubleNote,
  MusicNoteAdd: MusicNoteAdd,
  MusicNote: MusicNote,
  NavArrowDown: NavArrowDown,
  NavArrowLeft: NavArrowLeft,
  NavArrowRight: NavArrowRight,
  NavArrowUp: NavArrowUp,
  NavigatorAlt: NavigatorAlt,
  Navigator: Navigator,
  NetworkAlt: NetworkAlt,
  NetworkLeft: NetworkLeft,
  NetworkRight: NetworkRight,
  Network: Network,
  NewTab: NewTab,
  NintendoSwitch: NintendoSwitch,
  Nitrogen: Nitrogen,
  NoAccessWindow: NoAccessWindow,
  NoBattery: NoBattery,
  NoCoin: NoCoin,
  NoCreditCard: NoCreditCard,
  NoLink: NoLink,
  NoLock: NoLock,
  NoSmokingCircle: NoSmokingCircle,
  NoSmoking: NoSmoking,
  Notes: Notes,
  NpmSquare: NpmSquare,
  Npm: Npm,
  NumberedListLeft: NumberedListLeft,
  NumberedListRight: NumberedListRight,
  Octagon: Octagon,
  OffTag: OffTag,
  OilIndustry: OilIndustry,
  OnTag: OnTag,
  OneFingerSelectHandGesture: OneFingerSelectHandGesture,
  OnePointCircle: OnePointCircle,
  OpenBook: OpenBook,
  OpenInBrowser: OpenInBrowser,
  OpenInWindow: OpenInWindow,
  OpenNewWindow: OpenNewWindow,
  OpenSelectHandGesture: OpenSelectHandGesture,
  OpenVpn: OpenVpn,
  OrangeHalf: OrangeHalf,
  OrangeSliceAlt: OrangeSliceAlt,
  OrangeSlice: OrangeSlice,
  OrganicFoodSquare: OrganicFoodSquare,
  OrganicFood: OrganicFood,
  OrthogonalView: OrthogonalView,
  Oxygen: Oxygen,
  PackageLock: PackageLock,
  Package: Package,
  Packages: Packages,
  Pacman: Pacman,
  PageDown: PageDown,
  PageEdit: PageEdit,
  PageFlip: PageFlip,
  PageLeft: PageLeft,
  PageRight: PageRight,
  PageSearch: PageSearch,
  PageStar: PageStar,
  PageUp: PageUp,
  Page: Page,
  Palette: Palette,
  PanoramaEnlarge: PanoramaEnlarge,
  PanoramaReduce: PanoramaReduce,
  PantsAlt: PantsAlt,
  Pants: Pants,
  Parking: Parking,
  PasswordCursor: PasswordCursor,
  PasswordError: PasswordError,
  PasswordPass: PasswordPass,
  PasteClipboard: PasteClipboard,
  PathArrow: PathArrow,
  PauseWindow: PauseWindow,
  Pause: Pause,
  Paypal: Paypal,
  PcCheck: PcCheck,
  PcFirewall: PcFirewall,
  PcMouse: PcMouse,
  PcNoEntry: PcNoEntry,
  PcWarning: PcWarning,
  PeaceHand: PeaceHand,
  PenConnectBluetooth: PenConnectBluetooth,
  PenConnectWifi: PenConnectWifi,
  PenTabletConnectUsb: PenTabletConnectUsb,
  PenTabletConnectWifi: PenTabletConnectWifi,
  PenTablet: PenTablet,
  Pentagon: Pentagon,
  PeopleTag: PeopleTag,
  PercentageCircle: PercentageCircle,
  PercentageSquare: PercentageSquare,
  Percentage: Percentage,
  PerspectiveView: PerspectiveView,
  PharmacyCrossCircle: PharmacyCrossCircle,
  PharmacyCrossSquare: PharmacyCrossSquare,
  PhoneAdd: PhoneAdd,
  PhoneDelete: PhoneDelete,
  PhoneDisabled: PhoneDisabled,
  PhoneIncome: PhoneIncome,
  PhoneOutcome: PhoneOutcome,
  PhonePaused: PhonePaused,
  PhoneRemove: PhoneRemove,
  Phone: Phone,
  PiggyBank: PiggyBank,
  Pillow: Pillow,
  PinAlt: PinAlt,
  Pin: Pin,
  PineTree: PineTree,
  Pinterest: Pinterest,
  PizzaSlice: PizzaSlice,
  PlanetAlt: PlanetAlt,
  PlanetSat: PlanetSat,
  Planet: Planet,
  Play: Play,
  PlaylistAdd: PlaylistAdd,
  PlaylistPlay: PlaylistPlay,
  Playlist: Playlist,
  PlaystationGamepad: PlaystationGamepad,
  PlugTypeA: PlugTypeA,
  PlugTypeC: PlugTypeC,
  PlugTypeG: PlugTypeG,
  PlugTypeL: PlugTypeL,
  Plus: Plus,
  PngFormat: PngFormat,
  Pocket: Pocket,
  Podcast: Podcast,
  Pokeball: Pokeball,
  PositionAlign: PositionAlign,
  Position: Position,
  Potion: Potion,
  Pound: Pound,
  PrecisionTool: PrecisionTool,
  PrinterAlt: PrinterAlt,
  Printer: Printer,
  PrintingPage: PrintingPage,
  PriorityDown: PriorityDown,
  PriorityUp: PriorityUp,
  PrivateWifi: PrivateWifi,
  ProfileCircle: ProfileCircle,
  Prohibition: Prohibition,
  Puzzle: Puzzle,
  QrCode: QrCode,
  QuestionMark: QuestionMark,
  QuoteMessage: QuoteMessage,
  Quote: Quote,
  Radiation: Radiation,
  Radius: Radius,
  Rain: Rain,
  RawFormat: RawFormat,
  ReceiveDollars: ReceiveDollars,
  ReceiveEuros: ReceiveEuros,
  ReceivePounds: ReceivePounds,
  ReceiveYens: ReceiveYens,
  RedoAction: RedoAction,
  RedoCircle: RedoCircle,
  Redo: Redo,
  ReduceRoundArrow: ReduceRoundArrow,
  Reduce: Reduce,
  RefreshCircular: RefreshCircular,
  RefreshDouble: RefreshDouble,
  Refresh: Refresh,
  ReloadWindow: ReloadWindow,
  ReminderHandGesture: ReminderHandGesture,
  RemoveDatabaseScript: RemoveDatabaseScript,
  RemoveFolder: RemoveFolder,
  RemoveFrame: RemoveFrame,
  RemoveFromCart: RemoveFromCart,
  RemoveKeyframeAlt: RemoveKeyframeAlt,
  RemoveKeyframe: RemoveKeyframe,
  RemoveKeyframes: RemoveKeyframes,
  RemoveLink: RemoveLink,
  RemoveMediaImage: RemoveMediaImage,
  RemoveMediaVideo: RemoveMediaVideo,
  RemovePageAlt: RemovePageAlt,
  RemovePage: RemovePage,
  RemovePinAlt: RemovePinAlt,
  RemovePin: RemovePin,
  RemoveSelection: RemoveSelection,
  RemoveSquare: RemoveSquare,
  RemoveUser: RemoveUser,
  RepeatOnce: RepeatOnce,
  Repeat: Repeat,
  ReplyToMessage: ReplyToMessage,
  Reply: Reply,
  ReportColumns: ReportColumns,
  Reports: Reports,
  Repository: Repository,
  Restart: Restart,
  Rewind: Rewind,
  Rhombus: Rhombus,
  RightRoundArrow: RightRoundArrow,
  Rings: Rings,
  Rocket: Rocket,
  Rook: Rook,
  RotateCameraLeft: RotateCameraLeft,
  RotateCameraRight: RotateCameraRight,
  RoundFlask: RoundFlask,
  RoundedMirror: RoundedMirror,
  RssFeedTag: RssFeedTag,
  RssFeed: RssFeed,
  RubikCube: RubikCube,
  RulerAdd: RulerAdd,
  RulerCombine: RulerCombine,
  RulerRemove: RulerRemove,
  Ruler: Ruler,
  Running: Running,
  Safari: Safari,
  Sandals: Sandals,
  SaveActionFloppy: SaveActionFloppy,
  SaveFloppyDisk: SaveFloppyDisk,
  ScaleFrameEnlarge: ScaleFrameEnlarge,
  ScaleFrameReduce: ScaleFrameReduce,
  ScanBarcode: ScanBarcode,
  ScanQrCode: ScanQrCode,
  Scanning: Scanning,
  Scarf: Scarf,
  ScissorAlt: ScissorAlt,
  Scissor: Scissor,
  Screenshot: Screenshot,
  SeaAndSun: SeaAndSun,
  SeaWaves: SeaWaves,
  SearchEngine: SearchEngine,
  SearchFont: SearchFont,
  SearchWindow: SearchWindow,
  Search: Search,
  SecureWindow: SecureWindow,
  SecurityPass: SecurityPass,
  SelectWindow: SelectWindow,
  Selection: Selection,
  SelectiveTool: SelectiveTool,
  SendDiagonal: SendDiagonal,
  SendDollars: SendDollars,
  SendEuros: SendEuros,
  SendMail: SendMail,
  SendPounds: SendPounds,
  SendYens: SendYens,
  Send: Send,
  ServerConnection: ServerConnection,
  Server: Server,
  SettingsCloud: SettingsCloud,
  SettingsProfiles: SettingsProfiles,
  Settings: Settings,
  ShareAndroid: ShareAndroid,
  ShareIos: ShareIos,
  ShieldAdd: ShieldAdd,
  ShieldAlert: ShieldAlert,
  ShieldAlt: ShieldAlt,
  ShieldBroken: ShieldBroken,
  ShieldCheck: ShieldCheck,
  ShieldCross: ShieldCross,
  ShieldDownload: ShieldDownload,
  ShieldEye: ShieldEye,
  ShieldLoading: ShieldLoading,
  ShieldMinus: ShieldMinus,
  ShieldQuestion: ShieldQuestion,
  ShieldSearch: ShieldSearch,
  ShieldUpload: ShieldUpload,
  Shield: Shield,
  ShopAlt: ShopAlt,
  Shop: Shop,
  ShoppingBagAdd: ShoppingBagAdd,
  ShoppingBagAlt: ShoppingBagAlt,
  ShoppingBagArrowDown: ShoppingBagArrowDown,
  ShoppingBagArrowUp: ShoppingBagArrowUp,
  ShoppingBagCheck: ShoppingBagCheck,
  ShoppingBagIssue: ShoppingBagIssue,
  ShoppingBagRemove: ShoppingBagRemove,
  ShoppingBag: ShoppingBag,
  ShoppingCodeCheck: ShoppingCodeCheck,
  ShoppingCodeError: ShoppingCodeError,
  ShoppingCode: ShoppingCode,
  ShortPantsAlt: ShortPantsAlt,
  ShortPants: ShortPants,
  Shortcut: Shortcut,
  Shuffle: Shuffle,
  SidebarCollapse: SidebarCollapse,
  SidebarExpand: SidebarExpand,
  SigmaFunction: SigmaFunction,
  SimpleCart: SimpleCart,
  SingleTapGesture: SingleTapGesture,
  Skateboard: Skateboard,
  Skateboarding: Skateboarding,
  SkipNext: SkipNext,
  SkipPrev: SkipPrev,
  SleeperChair: SleeperChair,
  SmallLampAlt: SmallLampAlt,
  SmallLamp: SmallLamp,
  SmallShopAlt: SmallShopAlt,
  SmallShop: SmallShop,
  SmartphoneDevice: SmartphoneDevice,
  Smoking: Smoking,
  Snapchat: Snapchat,
  SnowFlake: SnowFlake,
  Snow: Snow,
  Soap: Soap,
  SoccerBall: SoccerBall,
  Sofa: Sofa,
  SoilAlt: SoilAlt,
  Soil: Soil,
  SortDown: SortDown,
  SortUp: SortUp,
  Sort: Sort,
  SoundHigh: SoundHigh,
  SoundLow: SoundLow,
  SoundMin: SoundMin,
  SoundOff: SoundOff,
  Spades: Spades,
  Sphere: Sphere,
  Spiral: Spiral,
  SpockHandGesture: SpockHandGesture,
  Square: Square,
  Stackoverflow: Stackoverflow,
  StarDashed: StarDashed,
  StarHalfDashed: StarHalfDashed,
  Star: Star,
  StatDown: StatDown,
  StatUp: StatUp,
  StatsDownSquare: StatsDownSquare,
  StatsReport: StatsReport,
  StatsUpSquare: StatsUpSquare,
  Stretching: Stretching,
  Stroller: Stroller,
  StyleBorder: StyleBorder,
  SubmitDocument: SubmitDocument,
  Substract: Substract,
  Suggestion: Suggestion,
  SunLight: SunLight,
  SvgFormat: SvgFormat,
  Swimming: Swimming,
  SwipeDownGesture: SwipeDownGesture,
  SwipeLeftGesture: SwipeLeftGesture,
  SwipeRightGesture: SwipeRightGesture,
  SwipeTwoFingersDownGesture: SwipeTwoFingersDownGesture,
  SwipeTwoFingersLeftGesture: SwipeTwoFingersLeftGesture,
  SwipeTwoFingersRightGesture: SwipeTwoFingersRightGesture,
  SwipeTwoFingersUpGesture: SwipeTwoFingersUpGesture,
  SwipeUpGesture: SwipeUpGesture,
  SwitchOff: SwitchOff,
  SwitchOn: SwitchOn,
  SystemRestart: SystemRestart,
  SystemShut: SystemShut,
  Table2Columns: Table2Columns,
  TableRows: TableRows,
  Table: Table,
  TaskList: TaskList,
  TelegramCircle: TelegramCircle,
  Telegram: Telegram,
  TennisBallAlt: TennisBallAlt,
  TennisBall: TennisBall,
  TerminalTag: TerminalTag,
  Terminal: Terminal,
  TestTube: TestTube,
  TextAlt: TextAlt,
  TextBox: TextBox,
  TextSize: TextSize,
  Text: Text,
  ThreePointsCircle: ThreePointsCircle,
  ThreeStars: ThreeStars,
  ThumbsDown: ThumbsDown,
  ThumbsUp: ThumbsUp,
  Thunderstorm: Thunderstorm,
  TifFormat: TifFormat,
  TiffFormat: TiffFormat,
  TikTok: TikTok,
  TimerOff: TimerOff,
  Timer: Timer,
  Tools: Tools,
  Tournament: Tournament,
  TowerCheck: TowerCheck,
  TowerNoAccess: TowerNoAccess,
  TowerWarning: TowerWarning,
  Tower: Tower,
  Trademark: Trademark,
  Train: Train,
  Tram: Tram,
  TransitionDown: TransitionDown,
  TransitionLeft: TransitionLeft,
  TransitionRight: TransitionRight,
  TransitionUp: TransitionUp,
  Translate: Translate,
  Trash: Trash,
  Treadmill: Treadmill,
  Tree: Tree,
  Trekking: Trekking,
  Trello: Trello,
  TriangleFlagCircle: TriangleFlagCircle,
  TriangleFlagTwoStripes: TriangleFlagTwoStripes,
  TriangleFlag: TriangleFlag,
  Triangle: Triangle,
  Trophy: Trophy,
  TruckLength: TruckLength,
  Truck: Truck,
  Tunnel: Tunnel,
  TvFix: TvFix,
  TvIssue: TvIssue,
  Tv: Tv,
  TwitterVerifiedBadge: TwitterVerifiedBadge,
  Twitter: Twitter,
  TwoPointsCircle: TwoPointsCircle,
  TwoSeaterSofa: TwoSeaterSofa,
  Type: Type,
  UmbrellaFull: UmbrellaFull,
  UnderlineSquare: UnderlineSquare,
  Underline: Underline,
  UndoAction: UndoAction,
  UndoCircle: UndoCircle,
  Undo: Undo,
  UnionAlt: UnionAlt,
  UnionHorizAlt: UnionHorizAlt,
  Union: Union,
  Unity5: Unity5,
  Unity: Unity,
  UpRoundArrow: UpRoundArrow,
  UploadDataWindow: UploadDataWindow,
  UploadSquare: UploadSquare,
  Upload: Upload,
  Usb: Usb,
  UserBag: UserBag,
  UserCart: UserCart,
  UserCircle: UserCircle,
  UserScan: UserScan,
  UserSquare: UserSquare,
  User: User,
  VeganCircle: VeganCircle,
  VeganSquare: VeganSquare,
  Vegan: Vegan,
  VerifiedBadge: VerifiedBadge,
  VerifiedUser: VerifiedUser,
  VerticalMerge: VerticalMerge,
  VerticalSplit: VerticalSplit,
  Vials: Vials,
  VideoCameraOff: VideoCameraOff,
  VideoCamera: VideoCamera,
  ViewColumns2: ViewColumns2,
  ViewColumns3: ViewColumns3,
  ViewGrid: ViewGrid,
  ViewStructureDown: ViewStructureDown,
  ViewStructureUp: ViewStructureUp,
  View360: View360,
  VoiceCircle: VoiceCircle,
  VoiceError: VoiceError,
  VoiceLockCircle: VoiceLockCircle,
  VoiceOk: VoiceOk,
  VoicePhone: VoicePhone,
  VoiceScan: VoiceScan,
  VoiceSquare: VoiceSquare,
  Voice: Voice,
  VrSymbol: VrSymbol,
  Waist: Waist,
  Walking: Walking,
  Wallet: Wallet,
  WarningCircle: WarningCircle,
  WarningHexagon: WarningHexagon,
  WarningSquare: WarningSquare,
  WarningTriangle: WarningTriangle,
  WarningWindow: WarningWindow,
  Wash: Wash,
  WashingMachine: WashingMachine,
  WateringSoil: WateringSoil,
  WebWindowClose: WebWindowClose,
  WebWindowEnergyConsumption: WebWindowEnergyConsumption,
  WebWindow: WebWindow,
  WebpFormat: WebpFormat,
  WeightAlt: WeightAlt,
  Weight: Weight,
  WhiteFlag: WhiteFlag,
  WifiError: WifiError,
  WifiIssue: WifiIssue,
  WifiOff: WifiOff,
  WifiSignalNone: WifiSignalNone,
  WifiTag: WifiTag,
  Wifi: Wifi,
  Wind: Wind,
  Windows: Windows,
  WrapText: WrapText,
  Wrench: Wrench,
  Wristwatch: Wristwatch,
  Www: Www,
  XCoordinate: XCoordinate,
  XboxA: XboxA,
  XboxB: XboxB,
  XboxX: XboxX,
  XboxY: XboxY,
  XrayView: XrayView,
  YCoordinate: YCoordinate,
  YenSquare: YenSquare,
  Yen: Yen,
  Yoga: Yoga,
  YouTube: YouTube,
  ZCoordinate: ZCoordinate,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
};
