name: Staging CI/CD

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  LATEST_IMAGE_TAG: latest-staging

jobs:
  test:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ secrets.AWS_TARGET_REGION }}
          role-session-name: 'GitHubActions-DeployLayerStack'

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Test 1
        run: |
          ls -l

      - name: Test 2
        run: |
          aws --version
          npm --version

      - name: Test 3
        run: |
          npm install -g aws-cdk 
          cdk --version

      - name: Test 4
        run: |
          cd django/mapa-cdk-test
          cdk list --context env=staging
