name: Staging CI/CD

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
    types: [closed]

env:
  LATEST_IMAGE_TAG: latest-staging

jobs:
  test:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Test 1
        run: |
          ls -l

      - name: Test 2
        run: |
          aws --version

      - name: Test 3
        run: |
          cdk --version
